SELECT mlv.idvisit
  , mlv.idsite
  , s.name AS site_name
  , s.main_url AS site_main_url
  , conv(HEX(mlv.idvisitor),16,16) AS idvisitor
  , mlv.visit_last_action_time
  , inet_ntoa(conv (HEX(mlv.location_ip),16,10)) AS location_ip
  , mlv.user_id
  , mlv.visit_first_action_time
  , mlv.visit_goal_buyer
  , mlv.visit_goal_converted
  , mlv.visitor_days_since_first
  , mlv.visitor_days_since_order
  , mlv.visitor_returning
  , mlv.visitor_count_visits
  , mlv.visit_entry_idaction_name
  , mlv.visit_entry_idaction_url
  , mlv.visit_exit_idaction_name
  , mlv.visit_exit_idaction_url
  , mlv.visit_total_actions
  , mlv.visit_total_interactions
  , mlv.visit_total_searches
  , mlv.referer_keyword
  , mlv.referer_name
  , mlv.referer_type
  , CASE
    WHEN mlv.referer_type = 1 THEN 'REFERRER_TYPE_DIRECT_ENTRY'
    WHEN mlv.referer_type = 2 THEN 'REFERRER_TYPE_SEARCH_ENGINE'
    WHEN mlv.referer_type = 3 THEN 'REFERRER_TYPE_WEBSITE'
    WHEN mlv.referer_type = 6 THEN 'REFERRER_TYPE_CAMPAIGN'
    ELSE 'Unknown'
  END AS referer_type_name
  , mlv.referer_url
  , mlv.location_browser_lang
  , left(mlv.location_browser_lang, 2) AS browser_lang
  , mlv.config_browser_engine
  , mlv.config_browser_name
  , CASE
    WHEN mlv.config_browser_name= '2B' THEN '2345 Browser'
    WHEN mlv.config_browser_name= '36' THEN '360 Phone Browser'
    WHEN mlv.config_browser_name= '3B' THEN '360 Browser'
    WHEN mlv.config_browser_name= 'AA' THEN 'Avant Browser'
    WHEN mlv.config_browser_name= 'AB' THEN 'ABrowse'
    WHEN mlv.config_browser_name= 'AF' THEN 'ANT Fresco'
    WHEN mlv.config_browser_name= 'AG' THEN 'ANTGalio'
    WHEN mlv.config_browser_name= 'AL' THEN 'Aloha Browser'
    WHEN mlv.config_browser_name= 'AH' THEN 'Aloha Browser Lite'
    WHEN mlv.config_browser_name= 'AM' THEN 'Amaya'
    WHEN mlv.config_browser_name= 'AO' THEN 'Amigo'
    WHEN mlv.config_browser_name= 'AN' THEN 'Android Browser'
    WHEN mlv.config_browser_name= 'AD' THEN 'AOL Shield'
    WHEN mlv.config_browser_name= 'AR' THEN 'Arora'
    WHEN mlv.config_browser_name= 'AV' THEN 'Amiga Voyager'
    WHEN mlv.config_browser_name= 'AW' THEN 'Amiga Aweb'
    WHEN mlv.config_browser_name= 'AT' THEN 'Atomic Web Browser'
    WHEN mlv.config_browser_name= 'AS' THEN 'Avast Secure Browser'
    WHEN mlv.config_browser_name= 'VG' THEN 'AVG Secure Browser'
    WHEN mlv.config_browser_name= 'BA' THEN 'Beaker Browser'
    WHEN mlv.config_browser_name= 'BM' THEN 'Beamrise'
    WHEN mlv.config_browser_name= 'BB' THEN 'BlackBerry Browser'
    WHEN mlv.config_browser_name= 'BD' THEN 'Baidu Browser'
    WHEN mlv.config_browser_name= 'BS' THEN 'Baidu Spark'
    WHEN mlv.config_browser_name= 'BI' THEN 'Basilisk'
    WHEN mlv.config_browser_name= 'BE' THEN 'Beonex'
    WHEN mlv.config_browser_name= 'BH' THEN 'BlackHawk'
    WHEN mlv.config_browser_name= 'BJ' THEN 'Bunjalloo'
    WHEN mlv.config_browser_name= 'BL' THEN 'B-Line'
    WHEN mlv.config_browser_name= 'BR' THEN 'Brave'
    WHEN mlv.config_browser_name= 'BK' THEN 'BriskBard'
    WHEN mlv.config_browser_name= 'BX' THEN 'BrowseX'
    WHEN mlv.config_browser_name= 'CA' THEN 'Camino'
    WHEN mlv.config_browser_name= 'CL' THEN 'CCleaner'
    WHEN mlv.config_browser_name= 'CC' THEN 'Coc Coc'
    WHEN mlv.config_browser_name= 'CD' THEN 'Comodo Dragon'
    WHEN mlv.config_browser_name= 'C1' THEN 'Coast'
    WHEN mlv.config_browser_name= 'CX' THEN 'Charon'
    WHEN mlv.config_browser_name= 'CE' THEN 'CM Browser'
    WHEN mlv.config_browser_name= 'CF' THEN 'Chrome Frame'
    WHEN mlv.config_browser_name= 'HC' THEN 'Headless Chrome'
    WHEN mlv.config_browser_name= 'CH' THEN 'Chrome'
    WHEN mlv.config_browser_name= 'CI' THEN 'Chrome Mobile iOS'
    WHEN mlv.config_browser_name= 'CK' THEN 'Conkeror'
    WHEN mlv.config_browser_name= 'CM' THEN 'Chrome Mobile'
    WHEN mlv.config_browser_name= 'CN' THEN 'CoolNovo'
    WHEN mlv.config_browser_name= 'CO' THEN 'CometBird'
    WHEN mlv.config_browser_name= 'CB' THEN 'COS Browser'
    WHEN mlv.config_browser_name= 'CP' THEN 'ChromePlus'
    WHEN mlv.config_browser_name= 'CR' THEN 'Chromium'
    WHEN mlv.config_browser_name= 'CY' THEN 'Cyberfox'
    WHEN mlv.config_browser_name= 'CS' THEN 'Cheshire'
    WHEN mlv.config_browser_name= 'CT' THEN 'Crusta'
    WHEN mlv.config_browser_name= 'CU' THEN 'Cunaguaro'
    WHEN mlv.config_browser_name= 'CV' THEN 'Chrome Webview'
    WHEN mlv.config_browser_name= 'DB' THEN 'dbrowser'
    WHEN mlv.config_browser_name= 'DE' THEN 'Deepnet Explorer'
    WHEN mlv.config_browser_name= 'DT' THEN 'Delta Browser'
    WHEN mlv.config_browser_name= 'DF' THEN 'Dolphin'
    WHEN mlv.config_browser_name= 'DO' THEN 'Dorado'
    WHEN mlv.config_browser_name= 'DL' THEN 'Dooble'
    WHEN mlv.config_browser_name= 'DI' THEN 'Dillo'
    WHEN mlv.config_browser_name= 'DD' THEN 'DuckDuckGo Privacy Browser'
    WHEN mlv.config_browser_name= 'EC' THEN 'Ecosia'
    WHEN mlv.config_browser_name= 'EI' THEN 'Epic'
    WHEN mlv.config_browser_name= 'EL' THEN 'Elinks'
    WHEN mlv.config_browser_name= 'EB' THEN 'Element Browser'
    WHEN mlv.config_browser_name= 'EZ' THEN 'eZ Browser'
    WHEN mlv.config_browser_name= 'EU' THEN 'EUI Browser'
    WHEN mlv.config_browser_name= 'EP' THEN 'GNOME Web'
    WHEN mlv.config_browser_name= 'ES' THEN 'Espial TV Browser'
    WHEN mlv.config_browser_name= 'FA' THEN 'Falkon'
    WHEN mlv.config_browser_name= 'FX' THEN 'Faux Browser'
    WHEN mlv.config_browser_name= 'F1' THEN 'Firefox Mobile iOS'
    WHEN mlv.config_browser_name= 'FB' THEN 'Firebird'
    WHEN mlv.config_browser_name= 'FD' THEN 'Fluid'
    WHEN mlv.config_browser_name= 'FE' THEN 'Fennec'
    WHEN mlv.config_browser_name= 'FF' THEN 'Firefox'
    WHEN mlv.config_browser_name= 'FK' THEN 'Firefox Focus'
    WHEN mlv.config_browser_name= 'FY' THEN 'Firefox Reality'
    WHEN mlv.config_browser_name= 'FR' THEN 'Firefox Rocket'
    WHEN mlv.config_browser_name= 'FL' THEN 'Flock'
    WHEN mlv.config_browser_name= 'FM' THEN 'Firefox Mobile'
    WHEN mlv.config_browser_name= 'FW' THEN 'Fireweb'
    WHEN mlv.config_browser_name= 'FN' THEN 'Fireweb Navigator'
    WHEN mlv.config_browser_name= 'FU' THEN 'FreeU'
    WHEN mlv.config_browser_name= 'GA' THEN 'Galeon'
    WHEN mlv.config_browser_name= 'GE' THEN 'Google Earth'
    WHEN mlv.config_browser_name= 'HA' THEN 'Hawk Turbo Browser'
    WHEN mlv.config_browser_name= 'HO' THEN 'hola! Browser'
    WHEN mlv.config_browser_name= 'HJ' THEN 'HotJava'
    WHEN mlv.config_browser_name= 'HU' THEN 'Huawei Browser'
    WHEN mlv.config_browser_name= 'IB' THEN 'IBrowse'
    WHEN mlv.config_browser_name= 'IC' THEN 'iCab'
    WHEN mlv.config_browser_name= 'I2' THEN 'iCab Mobile'
    WHEN mlv.config_browser_name= 'I1' THEN 'Iridium'
    WHEN mlv.config_browser_name= 'I3' THEN 'Iron Mobile'
    WHEN mlv.config_browser_name= 'I4' THEN 'IceCat'
    WHEN mlv.config_browser_name= 'ID' THEN 'IceDragon'
    WHEN mlv.config_browser_name= 'IV' THEN 'Isivioo'
    WHEN mlv.config_browser_name= 'IW' THEN 'Iceweasel'
    WHEN mlv.config_browser_name= 'IE' THEN 'Internet Explorer'
    WHEN mlv.config_browser_name= 'IM' THEN 'IE Mobile'
    WHEN mlv.config_browser_name= 'IR' THEN 'Iron'
    WHEN mlv.config_browser_name= 'JS' THEN 'Jasmine'
    WHEN mlv.config_browser_name= 'JI' THEN 'Jig Browser'
    WHEN mlv.config_browser_name= 'JO' THEN 'Jio Browser'
    WHEN mlv.config_browser_name= 'KB' THEN 'K.Browser'
    WHEN mlv.config_browser_name= 'KI' THEN 'Kindle Browser'
    WHEN mlv.config_browser_name= 'KM' THEN 'K-meleon'
    WHEN mlv.config_browser_name= 'KO' THEN 'Konqueror'
    WHEN mlv.config_browser_name= 'KP' THEN 'Kapiko'
    WHEN mlv.config_browser_name= 'KN' THEN 'Kinza'
    WHEN mlv.config_browser_name= 'KW' THEN 'Kiwi'
    WHEN mlv.config_browser_name= 'KY' THEN 'Kylo'
    WHEN mlv.config_browser_name= 'KZ' THEN 'Kazehakase'
    WHEN mlv.config_browser_name= 'LB' THEN 'Cheetah Browser'
    WHEN mlv.config_browser_name= 'LF' THEN 'LieBaoFast'
    WHEN mlv.config_browser_name= 'LG' THEN 'LG Browser'
    WHEN mlv.config_browser_name= 'LI' THEN 'Links'
    WHEN mlv.config_browser_name= 'LO' THEN 'Lovense Browser'
    WHEN mlv.config_browser_name= 'LU' THEN 'LuaKit'
    WHEN mlv.config_browser_name= 'LS' THEN 'Lunascape'
    WHEN mlv.config_browser_name= 'LX' THEN 'Lynx'
    WHEN mlv.config_browser_name= 'M1' THEN 'mCent'
    WHEN mlv.config_browser_name= 'MB' THEN 'MicroB'
    WHEN mlv.config_browser_name= 'MC' THEN 'NCSA Mosaic'
    WHEN mlv.config_browser_name= 'MZ' THEN 'Meizu Browser'
    WHEN mlv.config_browser_name= 'ME' THEN 'Mercury'
    WHEN mlv.config_browser_name= 'MF' THEN 'Mobile Safari'
    WHEN mlv.config_browser_name= 'MI' THEN 'Midori'
    WHEN mlv.config_browser_name= 'MO' THEN 'Mobicip'
    WHEN mlv.config_browser_name= 'MU' THEN 'MIUI Browser'
    WHEN mlv.config_browser_name= 'MS' THEN 'Mobile Silk'
    WHEN mlv.config_browser_name= 'MN' THEN 'Minimo'
    WHEN mlv.config_browser_name= 'MT' THEN 'Mint Browser'
    WHEN mlv.config_browser_name= 'MX' THEN 'Maxthon'
    WHEN mlv.config_browser_name= 'NB' THEN 'Nokia Browser'
    WHEN mlv.config_browser_name= 'NO' THEN 'Nokia OSS Browser'
    WHEN mlv.config_browser_name= 'NV' THEN 'Nokia Ovi Browser'
    WHEN mlv.config_browser_name= 'NX' THEN 'Nox Browser'
    WHEN mlv.config_browser_name= 'NE' THEN 'NetSurf'
    WHEN mlv.config_browser_name= 'NF' THEN 'NetFront'
    WHEN mlv.config_browser_name= 'NL' THEN 'NetFront Life'
    WHEN mlv.config_browser_name= 'NP' THEN 'NetPositive'
    WHEN mlv.config_browser_name= 'NS' THEN 'Netscape'
    WHEN mlv.config_browser_name= 'NT' THEN 'NTENT Browser'
    WHEN mlv.config_browser_name= 'OC' THEN 'Oculus Browser'
    WHEN mlv.config_browser_name= 'O1' THEN 'Opera Mini iOS'
    WHEN mlv.config_browser_name= 'OB' THEN 'Obigo'
    WHEN mlv.config_browser_name= 'OD' THEN 'Odyssey Web Browser'
    WHEN mlv.config_browser_name= 'OF' THEN 'Off By One'
    WHEN mlv.config_browser_name= 'OE' THEN 'ONE Browser'
    WHEN mlv.config_browser_name= 'OX' THEN 'Opera GX'
    WHEN mlv.config_browser_name= 'OG' THEN 'Opera Neon'
    WHEN mlv.config_browser_name= 'OH' THEN 'Opera Devices'
    WHEN mlv.config_browser_name= 'OI' THEN 'Opera Mini'
    WHEN mlv.config_browser_name= 'OM' THEN 'Opera Mobile'
    WHEN mlv.config_browser_name= 'OP' THEN 'Opera'
    WHEN mlv.config_browser_name= 'ON' THEN 'Opera Next'
    WHEN mlv.config_browser_name= 'OO' THEN 'Opera Touch'
    WHEN mlv.config_browser_name= 'OS' THEN 'Ordissimo'
    WHEN mlv.config_browser_name= 'OR' THEN 'Oregano'
    WHEN mlv.config_browser_name= 'OY' THEN 'Origyn Web Browser'
    WHEN mlv.config_browser_name= 'OV' THEN 'Openwave Mobile Browser'
    WHEN mlv.config_browser_name= 'OW' THEN 'OmniWeb'
    WHEN mlv.config_browser_name= 'OT' THEN 'Otter Browser'
    WHEN mlv.config_browser_name= 'PL' THEN 'Palm Blazer'
    WHEN mlv.config_browser_name= 'PM' THEN 'Pale Moon'
    WHEN mlv.config_browser_name= 'PP' THEN 'Oppo Browser'
    WHEN mlv.config_browser_name= 'PR' THEN 'Palm Pre'
    WHEN mlv.config_browser_name= 'PU' THEN 'Puffin'
    WHEN mlv.config_browser_name= 'PW' THEN 'Palm WebPro'
    WHEN mlv.config_browser_name= 'PA' THEN 'Palmscape'
    WHEN mlv.config_browser_name= 'PX' THEN 'Phoenix'
    WHEN mlv.config_browser_name= 'PO' THEN 'Polaris'
    WHEN mlv.config_browser_name= 'PT' THEN 'Polarity'
    WHEN mlv.config_browser_name= 'PS' THEN 'Microsoft Edge'
    WHEN mlv.config_browser_name= 'Q1' THEN 'QQ Browser Mini'
    WHEN mlv.config_browser_name= 'QQ' THEN 'QQ Browser'
    WHEN mlv.config_browser_name= 'QT' THEN 'Qutebrowser'
    WHEN mlv.config_browser_name= 'QZ' THEN 'QupZilla'
    WHEN mlv.config_browser_name= 'QM' THEN 'Qwant Mobile'
    WHEN mlv.config_browser_name= 'QW' THEN 'QtWebEngine'
    WHEN mlv.config_browser_name= 'RE' THEN 'Realme Browser'
    WHEN mlv.config_browser_name= 'RK' THEN 'Rekonq'
    WHEN mlv.config_browser_name= 'RM' THEN 'RockMelt'
    WHEN mlv.config_browser_name= 'SB' THEN 'Samsung Browser'
    WHEN mlv.config_browser_name= 'SA' THEN 'Sailfish Browser'
    WHEN mlv.config_browser_name= 'SC' THEN 'SEMC-Browser'
    WHEN mlv.config_browser_name= 'SE' THEN 'Sogou Explorer'
    WHEN mlv.config_browser_name= 'SF' THEN 'Safari'
    WHEN mlv.config_browser_name= 'SW' THEN 'SalamWeb'
    WHEN mlv.config_browser_name= 'SH' THEN 'Shiira'
    WHEN mlv.config_browser_name= 'S1' THEN 'SimpleBrowser'
    WHEN mlv.config_browser_name= 'SK' THEN 'Skyfire'
    WHEN mlv.config_browser_name= 'SS' THEN 'Seraphic Sraf'
    WHEN mlv.config_browser_name= 'SL' THEN 'Sleipnir'
    WHEN mlv.config_browser_name= 'SN' THEN 'Snowshoe'
    WHEN mlv.config_browser_name= 'SO' THEN 'Sogou Mobile Browser'
    WHEN mlv.config_browser_name= 'S2' THEN 'Splash'
    WHEN mlv.config_browser_name= 'SI' THEN 'Sputnik Browser'
    WHEN mlv.config_browser_name= 'SR' THEN 'Sunrise'
    WHEN mlv.config_browser_name= 'SP' THEN 'SuperBird'
    WHEN mlv.config_browser_name= 'SU' THEN 'Super Fast Browser'
    WHEN mlv.config_browser_name= 'S0' THEN 'START Internet Browser'
    WHEN mlv.config_browser_name= 'ST' THEN 'Streamy'
    WHEN mlv.config_browser_name= 'SX' THEN 'Swiftfox'
    WHEN mlv.config_browser_name= 'SZ' THEN 'Seznam Browser'
    WHEN mlv.config_browser_name= 'TO' THEN 't-online.de Browser'
    WHEN mlv.config_browser_name= 'TA' THEN 'Tao Browser'
    WHEN mlv.config_browser_name= 'TF' THEN 'TenFourFox'
    WHEN mlv.config_browser_name= 'TB' THEN 'Tenta Browser'
    WHEN mlv.config_browser_name= 'TZ' THEN 'Tizen Browser'
    WHEN mlv.config_browser_name= 'TS' THEN 'TweakStyle'
    WHEN mlv.config_browser_name= 'UB' THEN 'UBrowser'
    WHEN mlv.config_browser_name= 'UC' THEN 'UC Browser'
    WHEN mlv.config_browser_name= 'UM' THEN 'UC Browser Mini'
    WHEN mlv.config_browser_name= 'UT' THEN 'UC Browser Turbo'
    WHEN mlv.config_browser_name= 'UZ' THEN 'Uzbl'
    WHEN mlv.config_browser_name= 'VI' THEN 'Vivaldi'
    WHEN mlv.config_browser_name= 'VV' THEN 'vivo Browser'
    WHEN mlv.config_browser_name= 'VB' THEN 'Vision Mobile Browser'
    WHEN mlv.config_browser_name= 'WI' THEN 'Wear Internet Browser'
    WHEN mlv.config_browser_name= 'WP' THEN 'Web Explorer'
    WHEN mlv.config_browser_name= 'WE' THEN 'WebPositive'
    WHEN mlv.config_browser_name= 'WF' THEN 'Waterfox'
    WHEN mlv.config_browser_name= 'WH' THEN 'Whale Browser'
    WHEN mlv.config_browser_name= 'WO' THEN 'wOSBrowser'
    WHEN mlv.config_browser_name= 'WT' THEN 'WeTab Browser'
    WHEN mlv.config_browser_name= 'YA' THEN 'Yandex Browser'
    WHEN mlv.config_browser_name= 'YL' THEN 'Yandex Browser Lite'
    WHEN mlv.config_browser_name= 'XI' THEN 'Xiino'
    else 'Unknown'
  END AS config_browser_label
  , mlv.config_browser_version
  , mlv.config_device_brand
  , CASE
    WHEN mlv.config_device_brand= '3Q' THEN '3Q'
    WHEN mlv.config_device_brand= '4G' THEN '4Good'
    WHEN mlv.config_device_brand= 'AA' THEN 'AllCall'
    WHEN mlv.config_device_brand= 'AC' THEN 'Acer'
    WHEN mlv.config_device_brand= 'A9' THEN 'Advan'
    WHEN mlv.config_device_brand= 'AD' THEN 'Advance'
    WHEN mlv.config_device_brand= 'A3' THEN 'AGM'
    WHEN mlv.config_device_brand= 'AZ' THEN 'Ainol'
    WHEN mlv.config_device_brand= 'AI' THEN 'Airness'
    WHEN mlv.config_device_brand= '0A' THEN 'AIS'
    WHEN mlv.config_device_brand= 'AW' THEN 'Aiwa'
    WHEN mlv.config_device_brand= 'AK' THEN 'Akai'
    WHEN mlv.config_device_brand= '1A' THEN 'Alba'
    WHEN mlv.config_device_brand= 'AL' THEN 'Alcatel'
    WHEN mlv.config_device_brand= 'A2' THEN 'Allview'
    WHEN mlv.config_device_brand= 'A7' THEN 'Allwinner'
    WHEN mlv.config_device_brand= 'A1' THEN 'Altech UEC'
    WHEN mlv.config_device_brand= 'A5' THEN 'altron'
    WHEN mlv.config_device_brand= 'AN' THEN 'Arnova'
    WHEN mlv.config_device_brand= 'KN' THEN 'Amazon'
    WHEN mlv.config_device_brand= 'AG' THEN 'AMGOO'
    WHEN mlv.config_device_brand= 'AO' THEN 'Amoi'
    WHEN mlv.config_device_brand= 'AP' THEN 'Apple'
    WHEN mlv.config_device_brand= 'AR' THEN 'Archos'
    WHEN mlv.config_device_brand= 'AS' THEN 'ARRIS'
    WHEN mlv.config_device_brand= 'AB' THEN 'Arian Space'
    WHEN mlv.config_device_brand= 'AT' THEN 'Airties'
    WHEN mlv.config_device_brand= 'A6' THEN 'Ark'
    WHEN mlv.config_device_brand= 'A4' THEN 'Ask'
    WHEN mlv.config_device_brand= 'A8' THEN 'Assistant'
    WHEN mlv.config_device_brand= 'A0' THEN 'ANS'
    WHEN mlv.config_device_brand= 'AU' THEN 'Asus'
    WHEN mlv.config_device_brand= 'AH' THEN 'AVH'
    WHEN mlv.config_device_brand= 'AV' THEN 'Avvio'
    WHEN mlv.config_device_brand= 'AX' THEN 'Audiovox'
    WHEN mlv.config_device_brand= 'AY' THEN 'Axxion'
    WHEN mlv.config_device_brand= 'AM' THEN 'Azumi Mobile'
    WHEN mlv.config_device_brand= 'BB' THEN 'BBK'
    WHEN mlv.config_device_brand= 'BE' THEN 'Becker'
    WHEN mlv.config_device_brand= 'B5' THEN 'Beeline'
    WHEN mlv.config_device_brand= 'BI' THEN 'Bird'
    WHEN mlv.config_device_brand= 'BT' THEN 'Bitel'
    WHEN mlv.config_device_brand= 'BG' THEN 'BGH'
    WHEN mlv.config_device_brand= 'BL' THEN 'Beetel'
    WHEN mlv.config_device_brand= 'BP' THEN 'Blaupunkt'
    WHEN mlv.config_device_brand= 'B3' THEN 'Bluboo'
    WHEN mlv.config_device_brand= 'BF' THEN 'Black Fox'
    WHEN mlv.config_device_brand= 'B6' THEN 'BDF'
    WHEN mlv.config_device_brand= 'BM' THEN 'Bmobile'
    WHEN mlv.config_device_brand= 'BN' THEN 'Barnes & Noble'
    WHEN mlv.config_device_brand= 'BO' THEN 'BangOlufsen'
    WHEN mlv.config_device_brand= 'BQ' THEN 'BenQ'
    WHEN mlv.config_device_brand= 'BS' THEN 'BenQ-Siemens'
    WHEN mlv.config_device_brand= 'BU' THEN 'Blu'
    WHEN mlv.config_device_brand= 'BD' THEN 'Bluegood'
    WHEN mlv.config_device_brand= 'B2' THEN 'Blackview'
    WHEN mlv.config_device_brand= 'B4' THEN 'bogo'
    WHEN mlv.config_device_brand= 'BW' THEN 'Boway'
    WHEN mlv.config_device_brand= 'BX' THEN 'bq'
    WHEN mlv.config_device_brand= 'BV' THEN 'Bravis'
    WHEN mlv.config_device_brand= 'BR' THEN 'Brondi'
    WHEN mlv.config_device_brand= 'B1' THEN 'Bush'
    WHEN mlv.config_device_brand= 'CB' THEN 'CUBOT'
    WHEN mlv.config_device_brand= 'CF' THEN 'Carrefour'
    WHEN mlv.config_device_brand= 'CP' THEN 'Captiva'
    WHEN mlv.config_device_brand= 'CS' THEN 'Casio'
    WHEN mlv.config_device_brand= 'R4' THEN 'Casper'
    WHEN mlv.config_device_brand= 'CA' THEN 'Cat'
    WHEN mlv.config_device_brand= 'C9' THEN 'CAGI'
    WHEN mlv.config_device_brand= 'CE' THEN 'Celkon'
    WHEN mlv.config_device_brand= 'CC' THEN 'ConCorde'
    WHEN mlv.config_device_brand= 'C2' THEN 'Changhong'
    WHEN mlv.config_device_brand= 'CH' THEN 'Cherry Mobile'
    WHEN mlv.config_device_brand= 'L8' THEN 'Clarmin'
    WHEN mlv.config_device_brand= 'CK' THEN 'Cricket'
    WHEN mlv.config_device_brand= 'C1' THEN 'Crosscall'
    WHEN mlv.config_device_brand= 'CL' THEN 'Compal'
    WHEN mlv.config_device_brand= 'CN' THEN 'CnM'
    WHEN mlv.config_device_brand= 'CM' THEN 'Crius Mea'
    WHEN mlv.config_device_brand= 'C3' THEN 'China Mobile'
    WHEN mlv.config_device_brand= 'CR' THEN 'CreNova'
    WHEN mlv.config_device_brand= 'CT' THEN 'Capitel'
    WHEN mlv.config_device_brand= 'CQ' THEN 'Compaq'
    WHEN mlv.config_device_brand= 'CO' THEN 'Coolpad'
    WHEN mlv.config_device_brand= 'C5' THEN 'Condor'
    WHEN mlv.config_device_brand= 'CW' THEN 'Cowon'
    WHEN mlv.config_device_brand= 'CU' THEN 'Cube'
    WHEN mlv.config_device_brand= 'CY' THEN 'Coby Kyros'
    WHEN mlv.config_device_brand= 'C6' THEN 'Comio'
    WHEN mlv.config_device_brand= 'C7' THEN 'ComTrade Tesla'
    WHEN mlv.config_device_brand= 'C8' THEN 'Concord'
    WHEN mlv.config_device_brand= 'CX' THEN 'Crescent'
    WHEN mlv.config_device_brand= 'C4' THEN 'Cyrus'
    WHEN mlv.config_device_brand= 'CV' THEN 'CVTE'
    WHEN mlv.config_device_brand= 'DA' THEN 'Danew'
    WHEN mlv.config_device_brand= 'DT' THEN 'Datang'
    WHEN mlv.config_device_brand= 'D1' THEN 'Datsun'
    WHEN mlv.config_device_brand= 'DE' THEN 'Denver'
    WHEN mlv.config_device_brand= 'DX' THEN 'DEXP'
    WHEN mlv.config_device_brand= 'DS' THEN 'Desay'
    WHEN mlv.config_device_brand= 'DB' THEN 'Dbtel'
    WHEN mlv.config_device_brand= 'DC' THEN 'DoCoMo'
    WHEN mlv.config_device_brand= 'DG' THEN 'Dialog'
    WHEN mlv.config_device_brand= 'DI' THEN 'Dicam'
    WHEN mlv.config_device_brand= 'D4' THEN 'Digi'
    WHEN mlv.config_device_brand= 'D3' THEN 'Digicel'
    WHEN mlv.config_device_brand= 'DD' THEN 'Digiland'
    WHEN mlv.config_device_brand= 'D2' THEN 'Digma'
    WHEN mlv.config_device_brand= 'DL' THEN 'Dell'
    WHEN mlv.config_device_brand= 'DN' THEN 'DNS'
    WHEN mlv.config_device_brand= 'DM' THEN 'DMM'
    WHEN mlv.config_device_brand= 'DO' THEN 'Doogee'
    WHEN mlv.config_device_brand= 'DV' THEN 'Doov'
    WHEN mlv.config_device_brand= 'DP' THEN 'Dopod'
    WHEN mlv.config_device_brand= 'DR' THEN 'Doro'
    WHEN mlv.config_device_brand= 'DU' THEN 'Dune HD'
    WHEN mlv.config_device_brand= 'EB' THEN 'E-Boda'
    WHEN mlv.config_device_brand= 'EA' THEN 'EBEST'
    WHEN mlv.config_device_brand= 'EC' THEN 'Ericsson'
    WHEN mlv.config_device_brand= 'E7' THEN 'Ergo'
    WHEN mlv.config_device_brand= 'ED' THEN 'Energizer'
    WHEN mlv.config_device_brand= 'E4' THEN 'Echo Mobiles'
    WHEN mlv.config_device_brand= 'ES' THEN 'ECS'
    WHEN mlv.config_device_brand= 'E6' THEN 'EE'
    WHEN mlv.config_device_brand= 'EI' THEN 'Ezio'
    WHEN mlv.config_device_brand= 'EM' THEN 'Eks Mobility'
    WHEN mlv.config_device_brand= 'EL' THEN 'Elephone'
    WHEN mlv.config_device_brand= 'EG' THEN 'Elenberg'
    WHEN mlv.config_device_brand= 'EP' THEN 'Easypix'
    WHEN mlv.config_device_brand= 'EK' THEN 'EKO'
    WHEN mlv.config_device_brand= 'E1' THEN 'Energy Sistem'
    WHEN mlv.config_device_brand= 'ER' THEN 'Ericy'
    WHEN mlv.config_device_brand= 'EE' THEN 'Essential'
    WHEN mlv.config_device_brand= 'EN' THEN 'Eton'
    WHEN mlv.config_device_brand= 'E2' THEN 'Essentielb'
    WHEN mlv.config_device_brand= '1E' THEN 'Etuline'
    WHEN mlv.config_device_brand= 'ET' THEN 'eTouch'
    WHEN mlv.config_device_brand= 'EV' THEN 'Evertek'
    WHEN mlv.config_device_brand= 'E3' THEN 'Evolio'
    WHEN mlv.config_device_brand= 'EO' THEN 'Evolveo'
    WHEN mlv.config_device_brand= 'EX' THEN 'Explay'
    WHEN mlv.config_device_brand= 'E0' THEN 'EvroMedia'
    WHEN mlv.config_device_brand= 'E5' THEN 'Extrem'
    WHEN mlv.config_device_brand= 'EZ' THEN 'Ezze'
    WHEN mlv.config_device_brand= 'E8' THEN 'E-tel'
    WHEN mlv.config_device_brand= 'E9' THEN 'Evercoss'
    WHEN mlv.config_device_brand= 'EU' THEN 'Eurostar'
    WHEN mlv.config_device_brand= 'FA' THEN 'Fairphone'
    WHEN mlv.config_device_brand= 'FM' THEN 'Famoco'
    WHEN mlv.config_device_brand= 'FE' THEN 'Fengxiang'
    WHEN mlv.config_device_brand= 'FI' THEN 'FiGO'
    WHEN mlv.config_device_brand= 'FL' THEN 'Fly'
    WHEN mlv.config_device_brand= 'F1' THEN 'FinePower'
    WHEN mlv.config_device_brand= 'FT' THEN 'Freetel'
    WHEN mlv.config_device_brand= 'FR' THEN 'Forstar'
    WHEN mlv.config_device_brand= 'FO' THEN 'Foxconn'
    WHEN mlv.config_device_brand= 'F2' THEN 'FORME'
    WHEN mlv.config_device_brand= 'FN' THEN 'FNB'
    WHEN mlv.config_device_brand= 'FU' THEN 'Fujitsu'
    WHEN mlv.config_device_brand= 'FD' THEN 'Fondi'
    WHEN mlv.config_device_brand= 'GT' THEN 'G-TiDE'
    WHEN mlv.config_device_brand= 'GM' THEN 'Garmin-Asus'
    WHEN mlv.config_device_brand= 'GA' THEN 'Gateway'
    WHEN mlv.config_device_brand= 'GD' THEN 'Gemini'
    WHEN mlv.config_device_brand= 'GN' THEN 'General Mobile'
    WHEN mlv.config_device_brand= 'GE' THEN 'Geotel'
    WHEN mlv.config_device_brand= 'GH' THEN 'Ghia'
    WHEN mlv.config_device_brand= 'GI' THEN 'Gionee'
    WHEN mlv.config_device_brand= 'GG' THEN 'Gigabyte'
    WHEN mlv.config_device_brand= 'GS' THEN 'Gigaset'
    WHEN mlv.config_device_brand= 'GZ' THEN 'Ginzzu'
    WHEN mlv.config_device_brand= 'GC' THEN 'GOCLEVER'
    WHEN mlv.config_device_brand= 'GL' THEN 'Goly'
    WHEN mlv.config_device_brand= 'GO' THEN 'Google'
    WHEN mlv.config_device_brand= 'G1' THEN 'GoMobile'
    WHEN mlv.config_device_brand= 'GR' THEN 'Gradiente'
    WHEN mlv.config_device_brand= 'GP' THEN 'Grape'
    WHEN mlv.config_device_brand= 'GU' THEN 'Grundig'
    WHEN mlv.config_device_brand= 'HF' THEN 'Hafury'
    WHEN mlv.config_device_brand= 'HA' THEN 'Haier'
    WHEN mlv.config_device_brand= 'HS' THEN 'Hasee'
    WHEN mlv.config_device_brand= 'HE' THEN 'HannSpree'
    WHEN mlv.config_device_brand= 'HI' THEN 'Hisense'
    WHEN mlv.config_device_brand= 'HL' THEN 'Hi-Level'
    WHEN mlv.config_device_brand= 'H2' THEN 'Highscreen'
    WHEN mlv.config_device_brand= 'H1' THEN 'Hoffmann'
    WHEN mlv.config_device_brand= 'HM' THEN 'Homtom'
    WHEN mlv.config_device_brand= 'HO' THEN 'Hosin'
    WHEN mlv.config_device_brand= 'HZ' THEN 'Hoozo'
    WHEN mlv.config_device_brand= 'HP' THEN 'HP'
    WHEN mlv.config_device_brand= 'HT' THEN 'HTC'
    WHEN mlv.config_device_brand= 'HU' THEN 'Huawei'
    WHEN mlv.config_device_brand= 'HX' THEN 'Humax'
    WHEN mlv.config_device_brand= 'HY' THEN 'Hyrican'
    WHEN mlv.config_device_brand= 'HN' THEN 'Hyundai'
    WHEN mlv.config_device_brand= 'IA' THEN 'Ikea'
    WHEN mlv.config_device_brand= 'IB' THEN 'iBall'
    WHEN mlv.config_device_brand= 'IJ' THEN 'i-Joy'
    WHEN mlv.config_device_brand= 'IY' THEN 'iBerry'
    WHEN mlv.config_device_brand= 'IH' THEN 'iHunt'
    WHEN mlv.config_device_brand= 'IK' THEN 'iKoMo'
    WHEN mlv.config_device_brand= 'IE' THEN 'iView'
    WHEN mlv.config_device_brand= 'IM' THEN 'i-mate'
    WHEN mlv.config_device_brand= 'I1' THEN 'iOcean'
    WHEN mlv.config_device_brand= 'I2' THEN 'IconBIT'
    WHEN mlv.config_device_brand= 'IL' THEN 'IMO Mobile'
    WHEN mlv.config_device_brand= 'I7' THEN 'iLA'
    WHEN mlv.config_device_brand= 'IW' THEN 'iNew'
    WHEN mlv.config_device_brand= 'IP' THEN 'iPro'
    WHEN mlv.config_device_brand= 'IF' THEN 'Infinix'
    WHEN mlv.config_device_brand= 'I0' THEN 'InFocus'
    WHEN mlv.config_device_brand= 'I5' THEN 'InnJoo'
    WHEN mlv.config_device_brand= 'IN' THEN 'Innostream'
    WHEN mlv.config_device_brand= 'IS' THEN 'Insignia'
    WHEN mlv.config_device_brand= 'I4' THEN 'Inoi'
    WHEN mlv.config_device_brand= 'IR' THEN 'iRola'
    WHEN mlv.config_device_brand= 'I6' THEN 'Irbis'
    WHEN mlv.config_device_brand= 'II' THEN 'Inkti'
    WHEN mlv.config_device_brand= 'IX' THEN 'Intex'
    WHEN mlv.config_device_brand= 'IO' THEN 'i-mobile'
    WHEN mlv.config_device_brand= 'IQ' THEN 'INQ'
    WHEN mlv.config_device_brand= 'IT' THEN 'Intek'
    WHEN mlv.config_device_brand= 'IV' THEN 'Inverto'
    WHEN mlv.config_device_brand= 'I3' THEN 'Impression'
    WHEN mlv.config_device_brand= 'IZ' THEN 'iTel'
    WHEN mlv.config_device_brand= 'I9' THEN 'iZotron'
    WHEN mlv.config_device_brand= 'JA' THEN 'JAY-Tech'
    WHEN mlv.config_device_brand= 'JI' THEN 'Jiayu'
    WHEN mlv.config_device_brand= 'JO' THEN 'Jolla'
    WHEN mlv.config_device_brand= 'J5' THEN 'Just5'
    WHEN mlv.config_device_brand= 'KL' THEN 'Kalley'
    WHEN mlv.config_device_brand= 'K4' THEN 'Kaan'
    WHEN mlv.config_device_brand= 'KA' THEN 'Karbonn'
    WHEN mlv.config_device_brand= 'KD' THEN 'KDDI'
    WHEN mlv.config_device_brand= 'K1' THEN 'Kiano'
    WHEN mlv.config_device_brand= 'KI' THEN 'Kingsun'
    WHEN mlv.config_device_brand= 'KC' THEN 'Kocaso'
    WHEN mlv.config_device_brand= 'KG' THEN 'Kogan'
    WHEN mlv.config_device_brand= 'KO' THEN 'Konka'
    WHEN mlv.config_device_brand= 'KM' THEN 'Komu'
    WHEN mlv.config_device_brand= 'KB' THEN 'Koobee'
    WHEN mlv.config_device_brand= 'KT' THEN 'K-Touch'
    WHEN mlv.config_device_brand= 'KH' THEN 'KT-Tech'
    WHEN mlv.config_device_brand= 'KK' THEN 'Kodak'
    WHEN mlv.config_device_brand= 'KP' THEN 'KOPO'
    WHEN mlv.config_device_brand= 'KW' THEN 'Konrow'
    WHEN mlv.config_device_brand= 'KR' THEN 'Koridy'
    WHEN mlv.config_device_brand= 'K2' THEN 'KRONO'
    WHEN mlv.config_device_brand= 'KS' THEN 'Kempler & Strauss'
    WHEN mlv.config_device_brand= 'K3' THEN 'Keneksi'
    WHEN mlv.config_device_brand= 'KU' THEN 'Kumai'
    WHEN mlv.config_device_brand= 'KY' THEN 'Kyocera'
    WHEN mlv.config_device_brand= 'KZ' THEN 'Kazam'
    WHEN mlv.config_device_brand= 'KE' THEN 'Krüger&Matz'
    WHEN mlv.config_device_brand= 'LQ' THEN 'LAIQ'
    WHEN mlv.config_device_brand= 'L2' THEN 'Landvo'
    WHEN mlv.config_device_brand= 'L6' THEN 'Land Rover'
    WHEN mlv.config_device_brand= 'LV' THEN 'Lava'
    WHEN mlv.config_device_brand= 'LA' THEN 'Lanix'
    WHEN mlv.config_device_brand= 'LK' THEN 'Lark'
    WHEN mlv.config_device_brand= 'LC' THEN 'LCT'
    WHEN mlv.config_device_brand= 'L5' THEN 'Leagoo'
    WHEN mlv.config_device_brand= 'LD' THEN 'Ledstar'
    WHEN mlv.config_device_brand= 'L1' THEN 'LeEco'
    WHEN mlv.config_device_brand= 'L4' THEN 'Lemhoov'
    WHEN mlv.config_device_brand= 'LE' THEN 'Lenovo'
    WHEN mlv.config_device_brand= 'LN' THEN 'Lenco'
    WHEN mlv.config_device_brand= 'LT' THEN 'Leotec'
    WHEN mlv.config_device_brand= 'L7' THEN 'Lephone'
    WHEN mlv.config_device_brand= 'LP' THEN 'Le Pan'
    WHEN mlv.config_device_brand= 'LG' THEN 'LG'
    WHEN mlv.config_device_brand= 'LI' THEN 'Lingwin'
    WHEN mlv.config_device_brand= 'LO' THEN 'Loewe'
    WHEN mlv.config_device_brand= 'LM' THEN 'Logicom'
    WHEN mlv.config_device_brand= 'L3' THEN 'Lexand'
    WHEN mlv.config_device_brand= 'LX' THEN 'Lexibook'
    WHEN mlv.config_device_brand= 'LY' THEN 'LYF'
    WHEN mlv.config_device_brand= 'LU' THEN 'Lumus'
    WHEN mlv.config_device_brand= 'MN' THEN 'M4tel'
    WHEN mlv.config_device_brand= 'MJ' THEN 'Majestic'
    WHEN mlv.config_device_brand= 'MA' THEN 'Manta Multimedia'
    WHEN mlv.config_device_brand= '2M' THEN 'Masstel'
    WHEN mlv.config_device_brand= 'MW' THEN 'Maxwest'
    WHEN mlv.config_device_brand= 'M0' THEN 'Maze'
    WHEN mlv.config_device_brand= 'MB' THEN 'Mobistel'
    WHEN mlv.config_device_brand= '0M' THEN 'Mecool'
    WHEN mlv.config_device_brand= 'M3' THEN 'Mecer'
    WHEN mlv.config_device_brand= 'MD' THEN 'Medion'
    WHEN mlv.config_device_brand= 'M2' THEN 'MEEG'
    WHEN mlv.config_device_brand= 'M1' THEN 'Meizu'
    WHEN mlv.config_device_brand= '3M' THEN 'Meitu'
    WHEN mlv.config_device_brand= 'ME' THEN 'Metz'
    WHEN mlv.config_device_brand= 'MX' THEN 'MEU'
    WHEN mlv.config_device_brand= 'MI' THEN 'MicroMax'
    WHEN mlv.config_device_brand= 'M5' THEN 'MIXC'
    WHEN mlv.config_device_brand= 'MH' THEN 'Mobiola'
    WHEN mlv.config_device_brand= '4M' THEN 'Mobicel'
    WHEN mlv.config_device_brand= 'M6' THEN 'Mobiistar'
    WHEN mlv.config_device_brand= 'MC' THEN 'Mediacom'
    WHEN mlv.config_device_brand= 'MK' THEN 'MediaTek'
    WHEN mlv.config_device_brand= 'MO' THEN 'Mio'
    WHEN mlv.config_device_brand= 'M7' THEN 'Miray'
    WHEN mlv.config_device_brand= 'MM' THEN 'Mpman'
    WHEN mlv.config_device_brand= 'M4' THEN 'Modecom'
    WHEN mlv.config_device_brand= 'MF' THEN 'Mofut'
    WHEN mlv.config_device_brand= 'MR' THEN 'Motorola'
    WHEN mlv.config_device_brand= 'MV' THEN 'Movic'
    WHEN mlv.config_device_brand= 'MS' THEN 'Microsoft'
    WHEN mlv.config_device_brand= 'M9' THEN 'MTC'
    WHEN mlv.config_device_brand= 'MP' THEN 'MegaFon'
    WHEN mlv.config_device_brand= 'MZ' THEN 'MSI'
    WHEN mlv.config_device_brand= 'MU' THEN 'Memup'
    WHEN mlv.config_device_brand= 'MT' THEN 'Mitsubishi'
    WHEN mlv.config_device_brand= 'ML' THEN 'MLLED'
    WHEN mlv.config_device_brand= 'MQ' THEN 'M.T.T.'
    WHEN mlv.config_device_brand= 'N4' THEN 'MTN'
    WHEN mlv.config_device_brand= 'MY' THEN 'MyPhone'
    WHEN mlv.config_device_brand= '1M' THEN 'MYFON'
    WHEN mlv.config_device_brand= 'MG' THEN 'MyWigo'
    WHEN mlv.config_device_brand= 'M8' THEN 'Myria'
    WHEN mlv.config_device_brand= 'N3' THEN 'Navon'
    WHEN mlv.config_device_brand= 'N5' THEN 'NOA'
    WHEN mlv.config_device_brand= 'NE' THEN 'NEC'
    WHEN mlv.config_device_brand= 'NF' THEN 'Neffos'
    WHEN mlv.config_device_brand= 'NA' THEN 'Netgear'
    WHEN mlv.config_device_brand= 'NU' THEN 'NeuImage'
    WHEN mlv.config_device_brand= 'NG' THEN 'NGM'
    WHEN mlv.config_device_brand= 'N6' THEN 'Nobby'
    WHEN mlv.config_device_brand= 'NO' THEN 'Nous'
    WHEN mlv.config_device_brand= 'NI' THEN 'Nintendo'
    WHEN mlv.config_device_brand= 'N1' THEN 'Noain'
    WHEN mlv.config_device_brand= 'N2' THEN 'Nextbit'
    WHEN mlv.config_device_brand= 'NK' THEN 'Nokia'
    WHEN mlv.config_device_brand= 'NV' THEN 'Nvidia'
    WHEN mlv.config_device_brand= 'NB' THEN 'Noblex'
    WHEN mlv.config_device_brand= 'NM' THEN 'Nomi'
    WHEN mlv.config_device_brand= 'NL' THEN 'NUU Mobile'
    WHEN mlv.config_device_brand= 'NY' THEN 'NYX Mobile'
    WHEN mlv.config_device_brand= 'NN' THEN 'Nikon'
    WHEN mlv.config_device_brand= 'NW' THEN 'Newgen'
    WHEN mlv.config_device_brand= 'NX' THEN 'Nexian'
    WHEN mlv.config_device_brand= 'NT' THEN 'NextBook'
    WHEN mlv.config_device_brand= 'O3' THEN 'O+'
    WHEN mlv.config_device_brand= 'OB' THEN 'Obi'
    WHEN mlv.config_device_brand= 'O1' THEN 'Odys'
    WHEN mlv.config_device_brand= 'OD' THEN 'Onda'
    WHEN mlv.config_device_brand= 'ON' THEN 'OnePlus'
    WHEN mlv.config_device_brand= 'OP' THEN 'OPPO'
    WHEN mlv.config_device_brand= 'OR' THEN 'Orange'
    WHEN mlv.config_device_brand= 'OS' THEN 'Ordissimo'
    WHEN mlv.config_device_brand= 'OT' THEN 'O2'
    WHEN mlv.config_device_brand= 'OK' THEN 'Ouki'
    WHEN mlv.config_device_brand= 'OU' THEN 'OUYA'
    WHEN mlv.config_device_brand= 'OO' THEN 'Opsson'
    WHEN mlv.config_device_brand= 'OV' THEN 'Overmax'
    WHEN mlv.config_device_brand= 'OY' THEN 'Oysters'
    WHEN mlv.config_device_brand= 'OW' THEN 'öwn'
    WHEN mlv.config_device_brand= 'PN' THEN 'Panacom'
    WHEN mlv.config_device_brand= 'PA' THEN 'Panasonic'
    WHEN mlv.config_device_brand= 'PB' THEN 'PCBOX'
    WHEN mlv.config_device_brand= 'PC' THEN 'PCD'
    WHEN mlv.config_device_brand= 'PD' THEN 'PCD Argentina'
    WHEN mlv.config_device_brand= 'PE' THEN 'PEAQ'
    WHEN mlv.config_device_brand= 'PG' THEN 'Pentagram'
    WHEN mlv.config_device_brand= 'PH' THEN 'Philips'
    WHEN mlv.config_device_brand= 'PI' THEN 'Pioneer'
    WHEN mlv.config_device_brand= 'PX' THEN 'Pixus'
    WHEN mlv.config_device_brand= 'PL' THEN 'Polaroid'
    WHEN mlv.config_device_brand= 'P5' THEN 'Polytron'
    WHEN mlv.config_device_brand= 'P9' THEN 'Primepad'
    WHEN mlv.config_device_brand= 'PM' THEN 'Palm'
    WHEN mlv.config_device_brand= 'PO' THEN 'phoneOne'
    WHEN mlv.config_device_brand= 'PT' THEN 'Pantech'
    WHEN mlv.config_device_brand= 'PY' THEN 'Ployer'
    WHEN mlv.config_device_brand= 'P4' THEN 'Plum'
    WHEN mlv.config_device_brand= 'PV' THEN 'Point of View'
    WHEN mlv.config_device_brand= 'PP' THEN 'PolyPad'
    WHEN mlv.config_device_brand= 'P2' THEN 'Pomp'
    WHEN mlv.config_device_brand= 'P3' THEN 'PPTV'
    WHEN mlv.config_device_brand= 'PS' THEN 'Positivo'
    WHEN mlv.config_device_brand= 'PR' THEN 'Prestigio'
    WHEN mlv.config_device_brand= 'P1' THEN 'ProScan'
    WHEN mlv.config_device_brand= 'PU' THEN 'PULID'
    WHEN mlv.config_device_brand= 'QI' THEN 'Qilive'
    WHEN mlv.config_device_brand= 'QT' THEN 'Qtek'
    WHEN mlv.config_device_brand= 'QH' THEN 'Q-Touch'
    WHEN mlv.config_device_brand= 'QM' THEN 'QMobile'
    WHEN mlv.config_device_brand= 'QA' THEN 'Quantum'
    WHEN mlv.config_device_brand= 'QU' THEN 'Quechua'
    WHEN mlv.config_device_brand= 'RA' THEN 'Ramos'
    WHEN mlv.config_device_brand= 'RC' THEN 'RCA Tablets'
    WHEN mlv.config_device_brand= 'RB' THEN 'Readboy'
    WHEN mlv.config_device_brand= 'RI' THEN 'Rikomagic'
    WHEN mlv.config_device_brand= 'RN' THEN 'Rinno'
    WHEN mlv.config_device_brand= 'RV' THEN 'Riviera'
    WHEN mlv.config_device_brand= 'RM' THEN 'RIM'
    WHEN mlv.config_device_brand= 'RK' THEN 'Roku'
    WHEN mlv.config_device_brand= 'RO' THEN 'Rover'
    WHEN mlv.config_device_brand= 'R6' THEN 'RoverPad'
    WHEN mlv.config_device_brand= 'RR' THEN 'Roadrover'
    WHEN mlv.config_device_brand= 'R1' THEN 'Rokit'
    WHEN mlv.config_device_brand= 'R3' THEN 'Rombica'
    WHEN mlv.config_device_brand= 'RT' THEN 'RT Project'
    WHEN mlv.config_device_brand= 'RX' THEN 'Ritmix'
    WHEN mlv.config_device_brand= 'R5' THEN 'Ross&Moor'
    WHEN mlv.config_device_brand= 'R2' THEN 'R-TV'
    WHEN mlv.config_device_brand= 'SQ' THEN 'Santin BiTBiZ'
    WHEN mlv.config_device_brand= 'SA' THEN 'Samsung'
    WHEN mlv.config_device_brand= 'S0' THEN 'Sanei'
    WHEN mlv.config_device_brand= 'SD' THEN 'Sega'
    WHEN mlv.config_device_brand= 'SL' THEN 'Selfix'
    WHEN mlv.config_device_brand= 'SE' THEN 'Sony Ericsson'
    WHEN mlv.config_device_brand= 'S1' THEN 'Sencor'
    WHEN mlv.config_device_brand= 'SF' THEN 'Softbank'
    WHEN mlv.config_device_brand= 'SX' THEN 'SFR'
    WHEN mlv.config_device_brand= 'SG' THEN 'Sagem'
    WHEN mlv.config_device_brand= 'SH' THEN 'Sharp'
    WHEN mlv.config_device_brand= '3S' THEN 'Shuttle'
    WHEN mlv.config_device_brand= 'SI' THEN 'Siemens'
    WHEN mlv.config_device_brand= 'SJ' THEN 'Silent Circle'
    WHEN mlv.config_device_brand= '1S' THEN 'Sigma'
    WHEN mlv.config_device_brand= 'SN' THEN 'Sendo'
    WHEN mlv.config_device_brand= 'S6' THEN 'Senseit'
    WHEN mlv.config_device_brand= 'EW' THEN 'Senwa'
    WHEN mlv.config_device_brand= 'SW' THEN 'Sky'
    WHEN mlv.config_device_brand= 'SK' THEN 'Skyworth'
    WHEN mlv.config_device_brand= 'SC' THEN 'Smartfren'
    WHEN mlv.config_device_brand= 'SO' THEN 'Sony'
    WHEN mlv.config_device_brand= 'OI' THEN 'Sonim'
    WHEN mlv.config_device_brand= 'SP' THEN 'Spice'
    WHEN mlv.config_device_brand= 'SU' THEN 'SuperSonic'
    WHEN mlv.config_device_brand= 'S5' THEN 'Supra'
    WHEN mlv.config_device_brand= 'SV' THEN 'Selevision'
    WHEN mlv.config_device_brand= 'SY' THEN 'Sanyo'
    WHEN mlv.config_device_brand= 'SM' THEN 'Symphony'
    WHEN mlv.config_device_brand= '4S' THEN 'Syrox'
    WHEN mlv.config_device_brand= 'SR' THEN 'Smart'
    WHEN mlv.config_device_brand= 'S7' THEN 'Smartisan'
    WHEN mlv.config_device_brand= 'S4' THEN 'Star'
    WHEN mlv.config_device_brand= 'SB' THEN 'STF Mobile'
    WHEN mlv.config_device_brand= 'S8' THEN 'STK'
    WHEN mlv.config_device_brand= 'S9' THEN 'Savio'
    WHEN mlv.config_device_brand= '2S' THEN 'Starway'
    WHEN mlv.config_device_brand= 'ST' THEN 'Storex'
    WHEN mlv.config_device_brand= 'S2' THEN 'Stonex'
    WHEN mlv.config_device_brand= 'S3' THEN 'SunVan'
    WHEN mlv.config_device_brand= 'SZ' THEN 'Sumvision'
    WHEN mlv.config_device_brand= 'SS' THEN 'SWISSMOBILITY'
    WHEN mlv.config_device_brand= '10' THEN 'Simbans'
    WHEN mlv.config_device_brand= 'X1' THEN 'Safaricom'
    WHEN mlv.config_device_brand= 'TA' THEN 'Tesla'
    WHEN mlv.config_device_brand= 'T5' THEN 'TB Touch'
    WHEN mlv.config_device_brand= 'TC' THEN 'TCL'
    WHEN mlv.config_device_brand= 'T7' THEN 'Teclast'
    WHEN mlv.config_device_brand= 'TE' THEN 'Telit'
    WHEN mlv.config_device_brand= 'T4' THEN 'ThL'
    WHEN mlv.config_device_brand= 'TH' THEN 'TiPhone'
    WHEN mlv.config_device_brand= 'TB' THEN 'Tecno Mobile'
    WHEN mlv.config_device_brand= 'TP' THEN 'TechPad'
    WHEN mlv.config_device_brand= 'TD' THEN 'Tesco'
    WHEN mlv.config_device_brand= 'TI' THEN 'TIANYU'
    WHEN mlv.config_device_brand= 'TG' THEN 'Telego'
    WHEN mlv.config_device_brand= 'TL' THEN 'Telefunken'
    WHEN mlv.config_device_brand= 'T2' THEN 'Telenor'
    WHEN mlv.config_device_brand= 'TM' THEN 'T-Mobile'
    WHEN mlv.config_device_brand= 'TN' THEN 'Thomson'
    WHEN mlv.config_device_brand= 'TQ' THEN 'Timovi'
    WHEN mlv.config_device_brand= 'TY' THEN 'Tooky'
    WHEN mlv.config_device_brand= 'T1' THEN 'Tolino'
    WHEN mlv.config_device_brand= 'T9' THEN 'Top House'
    WHEN mlv.config_device_brand= 'TO' THEN 'Toplux'
    WHEN mlv.config_device_brand= 'T8' THEN 'Touchmate'
    WHEN mlv.config_device_brand= 'TS' THEN 'Toshiba'
    WHEN mlv.config_device_brand= 'TT' THEN 'TechnoTrend'
    WHEN mlv.config_device_brand= 'T6' THEN 'TrekStor'
    WHEN mlv.config_device_brand= 'T3' THEN 'Trevi'
    WHEN mlv.config_device_brand= 'TU' THEN 'Tunisie Telecom'
    WHEN mlv.config_device_brand= 'TR' THEN 'Turbo-X'
    WHEN mlv.config_device_brand= '1T' THEN 'Turbo'
    WHEN mlv.config_device_brand= '11' THEN 'True'
    WHEN mlv.config_device_brand= 'TV' THEN 'TVC'
    WHEN mlv.config_device_brand= 'TX' THEN 'TechniSat'
    WHEN mlv.config_device_brand= 'TZ' THEN 'teXet'
    WHEN mlv.config_device_brand= 'UC' THEN 'U.S. Cellular'
    WHEN mlv.config_device_brand= 'UH' THEN 'Uhappy'
    WHEN mlv.config_device_brand= 'UL' THEN 'Ulefone'
    WHEN mlv.config_device_brand= 'UO' THEN 'Unnecto'
    WHEN mlv.config_device_brand= 'UN' THEN 'Unowhy'
    WHEN mlv.config_device_brand= 'US' THEN 'Uniscope'
    WHEN mlv.config_device_brand= 'UX' THEN 'Unimax'
    WHEN mlv.config_device_brand= 'UM' THEN 'UMIDIGI'
    WHEN mlv.config_device_brand= 'UU' THEN 'Unonu'
    WHEN mlv.config_device_brand= 'UK' THEN 'UTOK'
    WHEN mlv.config_device_brand= 'UT' THEN 'UTStarcom'
    WHEN mlv.config_device_brand= 'VA' THEN 'Vastking'
    WHEN mlv.config_device_brand= 'VD' THEN 'Videocon'
    WHEN mlv.config_device_brand= 'VE' THEN 'Vertu'
    WHEN mlv.config_device_brand= 'VN' THEN 'Venso'
    WHEN mlv.config_device_brand= 'V5' THEN 'Vivax'
    WHEN mlv.config_device_brand= 'VI' THEN 'Vitelcom'
    WHEN mlv.config_device_brand= 'VK' THEN 'VK Mobile'
    WHEN mlv.config_device_brand= 'VS' THEN 'ViewSonic'
    WHEN mlv.config_device_brand= 'VT' THEN 'Vestel'
    WHEN mlv.config_device_brand= 'VR' THEN 'Vernee'
    WHEN mlv.config_device_brand= 'V4' THEN 'Verizon'
    WHEN mlv.config_device_brand= 'VL' THEN 'Verykool'
    WHEN mlv.config_device_brand= 'V6' THEN 'VGO TEL'
    WHEN mlv.config_device_brand= 'VV' THEN 'Vivo'
    WHEN mlv.config_device_brand= 'VX' THEN 'Vertex'
    WHEN mlv.config_device_brand= 'V3' THEN 'Vinsoc'
    WHEN mlv.config_device_brand= 'V2' THEN 'Vonino'
    WHEN mlv.config_device_brand= 'VG' THEN 'Vorago'
    WHEN mlv.config_device_brand= 'V1' THEN 'Voto'
    WHEN mlv.config_device_brand= 'VO' THEN 'Voxtel'
    WHEN mlv.config_device_brand= 'VF' THEN 'Vodafone'
    WHEN mlv.config_device_brand= 'VZ' THEN 'Vizio'
    WHEN mlv.config_device_brand= 'VW' THEN 'Videoweb'
    WHEN mlv.config_device_brand= 'VU' THEN 'Vulcan'
    WHEN mlv.config_device_brand= 'WA' THEN 'Walton'
    WHEN mlv.config_device_brand= 'WF' THEN 'Wileyfox'
    WHEN mlv.config_device_brand= 'WN' THEN 'Wink'
    WHEN mlv.config_device_brand= 'WM' THEN 'Weimei'
    WHEN mlv.config_device_brand= 'WE' THEN 'WellcoM'
    WHEN mlv.config_device_brand= 'WY' THEN 'Wexler'
    WHEN mlv.config_device_brand= 'WI' THEN 'Wiko'
    WHEN mlv.config_device_brand= 'WL' THEN 'Wolder'
    WHEN mlv.config_device_brand= 'WG' THEN 'Wolfgang'
    WHEN mlv.config_device_brand= 'WO' THEN 'Wonu'
    WHEN mlv.config_device_brand= 'W1' THEN 'Woo'
    WHEN mlv.config_device_brand= 'WX' THEN 'Woxter'
    WHEN mlv.config_device_brand= 'XV' THEN 'X-View'
    WHEN mlv.config_device_brand= 'XI' THEN 'Xiaomi'
    WHEN mlv.config_device_brand= 'XL' THEN 'Xiaolajiao'
    WHEN mlv.config_device_brand= 'XN' THEN 'Xion'
    WHEN mlv.config_device_brand= 'XO' THEN 'Xolo'
    WHEN mlv.config_device_brand= 'YA' THEN 'Yarvik'
    WHEN mlv.config_device_brand= 'YD' THEN 'Yandex'
    WHEN mlv.config_device_brand= 'Y2' THEN 'Yes'
    WHEN mlv.config_device_brand= 'YE' THEN 'Yezz'
    WHEN mlv.config_device_brand= 'Y1' THEN 'Yu'
    WHEN mlv.config_device_brand= 'YU' THEN 'Yuandao'
    WHEN mlv.config_device_brand= 'YS' THEN 'Yusun'
    WHEN mlv.config_device_brand= 'YT' THEN 'Ytone'
    WHEN mlv.config_device_brand= 'ZE' THEN 'Zeemi'
    WHEN mlv.config_device_brand= 'ZK' THEN 'Zenek'
    WHEN mlv.config_device_brand= 'ZO' THEN 'Zonda'
    WHEN mlv.config_device_brand= 'ZP' THEN 'Zopo'
    WHEN mlv.config_device_brand= 'ZT' THEN 'ZTE'
    WHEN mlv.config_device_brand= 'ZU' THEN 'Zuum'
    WHEN mlv.config_device_brand= 'ZN' THEN 'Zen'
    WHEN mlv.config_device_brand= 'ZY' THEN 'Zync'
    WHEN mlv.config_device_brand= 'ZQ' THEN 'ZYQ'
    WHEN mlv.config_device_brand= 'XT' THEN 'X-TIGI'
    WHEN mlv.config_device_brand= 'XB' THEN 'NEXBOX'
    ELSE 'Unknown'
  END AS config_device_brand_name
  , CASE
    WHEN mlv.config_browser_name IN ('AN', 'MU') THEN 'Android Browser'
    WHEN mlv.config_browser_name IN ('BB') THEN 'BlackBerry Browser'
    WHEN mlv.config_browser_name IN ('BD', 'BS') THEN 'Baidu'
    WHEN mlv.config_browser_name IN ('AV', 'AW') THEN 'Amiga'
    WHEN mlv.config_browser_name IN ('CH', 'BA', 'BR', 'CC', 'CD', 'CM', 'CI', 'CF', 'CN', 'CR', 'CP', 'DD', 'IR', 'RM', 'AO', 'TS', 'VI', 'PT', 'AS', 'TB', 'AD', 'SB', 'WP', 'I3', 'CV', 'WH', 'SZ', 'QW', 'LF', 'KW', '2B', 'CE', 'EC', 'MT', 'MS', 'HA', 'OC', 'MZ', 'BM', 'KN', 'SW', 'M1', 'FA', 'TA', 'AH', 'CL', 'SU', 'EU', 'UB', 'LO', 'VG') THEN 'Chrome'
    WHEN mlv.config_browser_name IN ('FF', 'FE', 'FM', 'SX', 'FB', 'PX', 'MB', 'EI', 'WF', 'CU', 'TF', 'QM', 'FR', 'I4', 'GZ', 'MO', 'F1', 'BI', 'MN', 'BH', 'TO', 'OS', 'FY') THEN 'Firefox'
    WHEN mlv.config_browser_name IN ('IE', 'IM', 'PS') THEN 'Internet Explorer'
    WHEN mlv.config_browser_name IN ('KO') THEN 'Konqueror'
    WHEN mlv.config_browser_name IN ('NF') THEN 'NetFront'
    WHEN mlv.config_browser_name IN ('NE') THEN 'NetSurf'
    WHEN mlv.config_browser_name IN ('NB', 'NO', 'NV', 'DO') THEN 'Nokia Browser'
    WHEN mlv.config_browser_name IN ('OP', 'OM', 'OI', 'ON', 'OO', 'OG', 'OH', 'O1', 'OX') THEN 'Opera'
    WHEN mlv.config_browser_name IN ('SF', 'MF', 'SO') THEN 'Safari'
    WHEN mlv.config_browser_name IN ('SA') THEN 'Sailfish Browser'
    ELSE 'Unknown'
  END AS config_browser_family
  , mlv.config_device_model
  , mlv.config_device_type
  , CASE
    WHEN mlv.config_device_type = 0 THEN 'DEVICE_TYPE_DESKTOP'
    WHEN mlv.config_device_type = 1 THEN 'DEVICE_TYPE_SMARTPHONE'
    WHEN mlv.config_device_type = 2 THEN 'DEVICE_TYPE_TABLET'
    WHEN mlv.config_device_type = 3 THEN 'DEVICE_TYPE_FEATURE_PHONE'
    WHEN mlv.config_device_type = 4 THEN 'DEVICE_TYPE_CONSOLE'
    WHEN mlv.config_device_type = 5 THEN 'DEVICE_TYPE_TV'
    WHEN mlv.config_device_type = 6 THEN 'DEVICE_TYPE_CAR_BROWSER'
    WHEN mlv.config_device_type = 7 THEN 'DEVICE_TYPE_SMART_DISPLAY'
    WHEN mlv.config_device_type = 8 THEN 'DEVICE_TYPE_CAMERA'
    WHEN mlv.config_device_type = 9 THEN 'DEVICE_TYPE_PORTABLE_MEDIA_PAYER'
    WHEN mlv.config_device_type = 10 THEN 'DEVICE_TYPE_PHABLET'
    WHEN mlv.config_device_type = 11 THEN 'DEVICE_TYPE_SMART_SPEAKER'
    ELSE 'Unknown'
  end AS config_device_type_code
  , CASE
    WHEN mlv.config_device_type = 0 THEN 'desktop'
    WHEN mlv.config_device_type = 1 THEN 'smartphone'
    WHEN mlv.config_device_type = 2 THEN 'tablet'
    WHEN mlv.config_device_type = 3 THEN 'feature phone'
    WHEN mlv.config_device_type = 4 THEN 'console'
    WHEN mlv.config_device_type = 5 THEN 'tv'
    WHEN mlv.config_device_type = 6 THEN 'car browser'
    WHEN mlv.config_device_type = 7 THEN 'smart display'
    WHEN mlv.config_device_type = 8 THEN 'camera'
    WHEN mlv.config_device_type = 9 THEN 'portable media player'
    WHEN mlv.config_device_type = 10 THEN 'phablet'
    WHEN mlv.config_device_type = 11 THEN 'smart speaker'
    ELSE 'Unknown'
  END AS config_device_type_name
  , mlv.config_os
  , CASE
    WHEN mlv.config_os= 'AIX' THEN 'AIX'
    WHEN mlv.config_os= 'AND' THEN 'Android'
    WHEN mlv.config_os= 'AMG' THEN 'AmigaOS'
    WHEN mlv.config_os= 'ATV' THEN 'Apple TV'
    WHEN mlv.config_os= 'ARL' THEN 'Arch Linux'
    WHEN mlv.config_os= 'BTR' THEN 'BackTrack'
    WHEN mlv.config_os= 'SBA' THEN 'Bada'
    WHEN mlv.config_os= 'BEO' THEN 'BeOS'
    WHEN mlv.config_os= 'BLB' THEN 'BlackBerry OS'
    WHEN mlv.config_os= 'QNX' THEN 'BlackBerry Tablet OS'
    WHEN mlv.config_os= 'BMP' THEN 'Brew'
    WHEN mlv.config_os= 'CES' THEN 'CentOS'
    WHEN mlv.config_os= 'COS' THEN 'Chrome OS'
    WHEN mlv.config_os= 'CYN' THEN 'CyanogenMod'
    WHEN mlv.config_os= 'DEB' THEN 'Debian'
    WHEN mlv.config_os= 'DFB' THEN 'DragonFly'
    WHEN mlv.config_os= 'FED' THEN 'Fedora'
    WHEN mlv.config_os= 'FOS' THEN 'Firefox OS'
    WHEN mlv.config_os= 'FIR' THEN 'Fire OS'
    WHEN mlv.config_os= 'BSD' THEN 'FreeBSD'
    WHEN mlv.config_os= 'GNT' THEN 'Gentoo'
    WHEN mlv.config_os= 'GTV' THEN 'Google TV'
    WHEN mlv.config_os= 'HPX' THEN 'HP-UX'
    WHEN mlv.config_os= 'HAI' THEN 'Haiku OS'
    WHEN mlv.config_os= 'IRI' THEN 'IRIX'
    WHEN mlv.config_os= 'INF' THEN 'Inferno'
    WHEN mlv.config_os= 'KOS' THEN 'KaiOS'
    WHEN mlv.config_os= 'KNO' THEN 'Knoppix'
    WHEN mlv.config_os= 'KBT' THEN 'Kubuntu'
    WHEN mlv.config_os= 'LIN' THEN 'GNU/Linux'
    WHEN mlv.config_os= 'LBT' THEN 'Lubuntu'
    WHEN mlv.config_os= 'VLN' THEN 'VectorLinux'
    WHEN mlv.config_os= 'MAC' THEN 'Mac'
    WHEN mlv.config_os= 'MAE' THEN 'Maemo'
    WHEN mlv.config_os= 'MDR' THEN 'Mandriva'
    WHEN mlv.config_os= 'SMG' THEN 'MeeGo'
    WHEN mlv.config_os= 'MCD' THEN 'MocorDroid'
    WHEN mlv.config_os= 'MIN' THEN 'Mint'
    WHEN mlv.config_os= 'MLD' THEN 'MildWild'
    WHEN mlv.config_os= 'MOR' THEN 'MorphOS'
    WHEN mlv.config_os= 'NBS' THEN 'NetBSD'
    WHEN mlv.config_os= 'MTK' THEN 'MTK / Nucleus'
    WHEN mlv.config_os= 'WII' THEN 'Nintendo'
    WHEN mlv.config_os= 'NDS' THEN 'Nintendo Mobile'
    WHEN mlv.config_os= 'OS2' THEN 'OS/2'
    WHEN mlv.config_os= 'T64' THEN 'OSF1'
    WHEN mlv.config_os= 'OBS' THEN 'OpenBSD'
    WHEN mlv.config_os= 'ORD' THEN 'Ordissimo'
    WHEN mlv.config_os= 'PSP' THEN 'PlayStation Portable'
    WHEN mlv.config_os= 'PS3' THEN 'PlayStation'
    WHEN mlv.config_os= 'RHT' THEN 'Red Hat'
    WHEN mlv.config_os= 'ROS' THEN 'RISC OS'
    WHEN mlv.config_os= 'REM' THEN 'Remix OS'
    WHEN mlv.config_os= 'RZD' THEN 'RazoDroiD'
    WHEN mlv.config_os= 'SAB' THEN 'Sabayon'
    WHEN mlv.config_os= 'SSE' THEN 'SUSE'
    WHEN mlv.config_os= 'SAF' THEN 'Sailfish OS'
    WHEN mlv.config_os= 'SLW' THEN 'Slackware'
    WHEN mlv.config_os= 'SOS' THEN 'Solaris'
    WHEN mlv.config_os= 'SYL' THEN 'Syllable'
    WHEN mlv.config_os= 'SYM' THEN 'Symbian'
    WHEN mlv.config_os= 'SYS' THEN 'Symbian OS'
    WHEN mlv.config_os= 'S40' THEN 'Symbian OS Series 40'
    WHEN mlv.config_os= 'S60' THEN 'Symbian OS Series 60'
    WHEN mlv.config_os= 'SY3' THEN 'Symbian^3'
    WHEN mlv.config_os= 'TDX' THEN 'ThreadX'
    WHEN mlv.config_os= 'TIZ' THEN 'Tizen'
    WHEN mlv.config_os= 'UBT' THEN 'Ubuntu'
    WHEN mlv.config_os= 'WTV' THEN 'WebTV'
    WHEN mlv.config_os= 'WIN' THEN 'Windows'
    WHEN mlv.config_os= 'WCE' THEN 'Windows CE'
    WHEN mlv.config_os= 'WIO' THEN 'Windows IoT'
    WHEN mlv.config_os= 'WMO' THEN 'Windows Mobile'
    WHEN mlv.config_os= 'WPH' THEN 'Windows Phone'
    WHEN mlv.config_os= 'WRT' THEN 'Windows RT'
    WHEN mlv.config_os= 'XBX' THEN 'Xbox'
    WHEN mlv.config_os= 'XBT' THEN 'Xubuntu'
    WHEN mlv.config_os= 'YNS' THEN 'YunOs'
    WHEN mlv.config_os= 'IOS' THEN 'iOS'
    WHEN mlv.config_os= 'POS' THEN 'palmOS'
    WHEN mlv.config_os= 'WOS' THEN 'webOS'
  END AS config_os_name
  , CASE
    WHEN mlv.config_os IN ('AND', 'CYN', 'FIR', 'REM', 'RZD', 'MLD', 'MCD', 'YNS') THEN 'Android'
    WHEN mlv.config_os IN ('AMG', 'MOR') THEN 'AmigaOS'
    WHEN mlv.config_os IN ('ATV') THEN 'Apple TV'
    WHEN mlv.config_os IN ('BLB', 'QNX') THEN 'BlackBerry'
    WHEN mlv.config_os IN ('BMP') THEN 'Brew'
    WHEN mlv.config_os IN ('BEO', 'HAI') THEN 'BeOS'
    WHEN mlv.config_os IN ('COS') THEN 'Chrome OS'
    WHEN mlv.config_os IN ('FOS', 'KOS') THEN 'Firefox OS'
    WHEN mlv.config_os IN ('WII', 'PS3') THEN 'Gaming Console'
    WHEN mlv.config_os IN ('GTV') THEN 'Google TV'
    WHEN mlv.config_os IN ('OS2') THEN 'IBM'
    WHEN mlv.config_os IN ('IOS') THEN 'iOS'
    WHEN mlv.config_os IN ('ROS') THEN 'RISC OS'
    WHEN mlv.config_os IN ('LIN', 'ARL', 'DEB', 'KNO', 'MIN', 'UBT', 'KBT', 'XBT', 'LBT', 'FED', 'RHT', 'VLN', 'MDR', 'GNT', 'SAB', 'SLW', 'SSE', 'CES', 'BTR', 'SAF', 'ORD') THEN 'GNU/Linux'
    WHEN mlv.config_os IN ('MAC') THEN 'Mac'
    WHEN mlv.config_os IN ('PSP', 'NDS', 'XBX') THEN 'Mobile Gaming Console'
    WHEN mlv.config_os IN ('MTK', 'TDX') THEN 'Real-time OS'
    WHEN mlv.config_os IN ('WOS', 'POS', 'SBA', 'TIZ', 'SMG', 'MAE') THEN 'Other Mobile'
    WHEN mlv.config_os IN ('SYM', 'SYS', 'SY3', 'S60', 'S40') THEN 'Symbian'
    WHEN mlv.config_os IN ('SOS', 'AIX', 'HPX', 'BSD', 'NBS', 'OBS', 'DFB', 'SYL', 'IRI', 'T64', 'INF') THEN 'Unix'
    WHEN mlv.config_os IN ('WTV') THEN 'WebTV'
    WHEN mlv.config_os IN ('WIN') THEN 'Windows'
    WHEN mlv.config_os IN ('WPH', 'WMO', 'WCE', 'WRT', 'WIO') THEN 'Windows Mobile'
  END AS config_os_family
  , mlv.config_os_version
  , mlv.visit_total_events
  , mlv.visitor_localtime
  , mlv.visitor_days_since_last
  , mlv.config_resolution
  , mlv.config_cookie
  , mlv.config_director
  , mlv.config_flash
  , mlv.config_gears
  , mlv.config_java
  , mlv.config_pdf
  , mlv.config_quicktime
  , mlv.config_realplayer
  , mlv.config_silverlight
  , mlv.config_windowsmedia
  , mlv.visit_total_time
  , mlv.location_city
  , mlv.location_country
  , mlv.location_latitude
  , mlv.location_longitude
  , mlv.location_region
  , mlv.custom_var_k1
  , mlv.custom_var_v1
  , mlv.custom_var_k2
  , mlv.custom_var_v2
  , mlv.custom_var_k3
  , mlv.custom_var_v3
  , mlv.custom_var_k4
  , mlv.custom_var_v4
  , mlv.custom_var_k5
  , mlv.custom_var_v5
  , mlv.last_idlink_va
  , mlv.custom_dimension_1
  , mlv.custom_dimension_2
  , mlv.custom_dimension_3
  , mlv.custom_dimension_4
  , mlv.custom_dimension_5
  , mlv.campaign_content
  , mlv.campaign_id
  , mlv.campaign_keyword
  , mlv.campaign_medium
  , mlv.campaign_name
  , mlv.Campaign_source
  , CURRENT_TIMESTAMP(6) AS etl_create_date_string
  , CURRENT_TIMESTAMP(6) AS etl_update_date_string
  , UNIX_TIMESTAMP(now()) AS etl_create_date_unix
  , UNIX_TIMESTAMP(now()) AS etl_update_date_unix
FROM matomo.matomo_log_visit mlv
JOIN matomo.matomo_site s
ON s.idsite = mlv.idsite
WHERE s.idsite = 4
AND mlv.idvisit > {{.idvisit}}
LIMIT 10
;
